version: '3.5'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    environment:
      - "DB_PORT=${DB_PORT}"
      - "DB_HOST=${DB_HOST}"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
  
  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"

  # The Composer
  composer:
    tty: true
    image: library/composer
    working_dir: /var/www/html
    command: bash -c "composer install --no-scripts --no-autoloader && composer dump-autoload --optimize"
    volumes:
      - ./:/var/www/html

volumes:
  dbdata: